backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "general"
    label: "General"
    files:
      - label: "Dictionary"
        name: "dictionary"
        file: "content/general/dictionary.md"
        fields:
          - label: "Labels"
            name: "labels"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
