backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "general"
    label: "General"
    files:
      - label: "Dictionary"
        name: "dictionary"
        file: "content/general/dictionary.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
      - label: "Headings"
        name: "headings"
        file: "content/general/headings.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
      - label: "Copy"
        name: "copy"
        file: "content/general/copy.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "text" }
      - label: "Tags"
        name: "tags"
        file: "content/general/tags.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "text" }
  - name: "resume"
    label: "Resume"
    files:
      - label: "Work experience"
        name: "workExperience"
        file: "content/resume/workExperience.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Company", name: "company", widget: "string" }
              - {
                  label: "CompanyWebsite",
                  name: "companyWebsite",
                  widget: "string",
                }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Date", name: "startDate", widget: "datetime" }
              - { label: "Date", name: "endDate", widget: "datetime" }
              - { label: "Present", name: "present", widget: "boolean" }
              - { label: "City", name: "city", widget: "string" }
              - { label: "Country code", name: "countryCode", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Articles"
    files:
      - label: "Articles"
        name: "articles"
        file: "content/articles/articles.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - {
                  label: "Tags",
                  name: "tags",
                  widget: "relation",
                  collection: "tags",
                  searchFields: ["key"],
                  valueField: "key",
                  multiple: true,
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Teaser Copy", name: "teaserCopy", widget: "text" }
              - { label: "Teaser Image", name: "teaserImage", widget: "image" }
              - { label: "Intro", name: "intro", widget: "markdown" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "Quick Bits"
        name: "quickBits"
        file: "content/articles/quickBits.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - {
                  label: "Tags",
                  name: "tags",
                  widget: "relation",
                  collection: "tags",
                  searchFields: ["key"],
                  valueField: "key",
                  multiple: true,
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Teaser Copy", name: "teaserCopy", widget: "text" }
              - { label: "Teaser Image", name: "teaserImage", widget: "image" }
              - { label: "Intro", name: "intro", widget: "markdown" }
              - { label: "Body", name: "body", widget: "markdown" }
