backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "general"
    label: "General"
    files:
      - label: "Dictionary"
        name: "dictionary"
        file: "content/general/dictionary.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
      - label: "Headings"
        name: "headings"
        file: "content/general/headings.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
      - label: "Copy"
        name: "copy"
        file: "content/general/copy.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Value", name: "value", widget: "text" }
  - name: "articles"
    label: "Articles"
    files:
      - label: "Articles"
        name: "articles"
        file: "content/articles/articles.md"
        fields:
          - label: "Items"
            name: "items"
            widget: list
            fields:
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Teaser Copy", name: "teaserCopy", widget: "text" }
              - { label: "Teaser Image", name: "teaserImage", widget: "image" }
              - { label: "Intro", name: "teaserImage", widget: "markdown" }
              - { label: "Body", name: "body", widget: "markdown" }
