name: Trigger Netlify Build
on:
  schedule:
    # Run at 12:05 on Friday
    - cron: "05 12 * * 5"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/61080485234cb0f6cc818a31
